/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.escritores;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.saxon.s9api.SaxonApiException;
import org.jdom2.Document;

/**
 *
 * @author paulo
 */
public class Frame extends javax.swing.JFrame {
    private Map<String, String> data;
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        adicionarEscritorDialog = new javax.swing.JDialog();
        nomeEscritorTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        adicionarEscritorButton = new javax.swing.JButton();
        removerEscritorDialog = new javax.swing.JDialog();
        nomeEscritorTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        removerEscritorButton = new javax.swing.JButton();
        pesquisarEscritorDialog = new javax.swing.JDialog();
        nomeEscritorTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pesquisarEscritorButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        informacaoTextArea = new javax.swing.JTextArea();
        pesquisarNacionalidadeDialog = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        pesquisarNacionalidadeButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        autoresTextArea = new javax.swing.JTextArea();
        nomeNacionalidadeTextField = new javax.swing.JTextField();
        pesquisarObrasEscritorDialog = new javax.swing.JDialog();
        nomeEscritorTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pesquisarObrasButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        obrasEscritorTextArea = new javax.swing.JTextArea();
        editarEscritorDialog = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        alterarEscritorButton = new javax.swing.JButton();
        nomeEscritorTextField3 = new javax.swing.JTextField();
        nomeRadioButton = new javax.swing.JRadioButton();
        dNascimentoRadioButton = new javax.swing.JRadioButton();
        nacionalidadeRadioButton = new javax.swing.JRadioButton();
        ocupacaoRadioButton = new javax.swing.JRadioButton();
        dFalecimentoRadioButton = new javax.swing.JRadioButton();
        premiosRadioButton = new javax.swing.JRadioButton();
        gLiterarioRadioButton = new javax.swing.JRadioButton();
        alterarTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        enviarEscritorButton = new javax.swing.JButton();
        buttonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        principalMenu = new javax.swing.JMenu();
        abrirMenuItem = new javax.swing.JMenuItem();
        sairMenuItem = new javax.swing.JMenuItem();
        xmlMenu = new javax.swing.JMenu();
        adicionarEscritorMenuItem = new javax.swing.JMenuItem();
        removerEscritorMenuItem = new javax.swing.JMenuItem();
        editarEscritorMenuItem = new javax.swing.JMenuItem();
        xPathMenu = new javax.swing.JMenu();
        pesquisarEscritorMenuItem = new javax.swing.JMenuItem();
        pesquisarNacionalidadeMenuItem = new javax.swing.JMenuItem();
        pesquisarObrasEscritorMenuItem = new javax.swing.JMenuItem();
        escritorPremiadoMenuItem = new javax.swing.JMenuItem();
        validarMenu = new javax.swing.JMenu();
        DTDMenuItem = new javax.swing.JMenuItem();
        XSDMenuItem = new javax.swing.JMenuItem();

        nomeEscritorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEscritorTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Escritor:");

        adicionarEscritorButton.setText("Adicionar Autor");
        adicionarEscritorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEscritorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adicionarEscritorDialogLayout = new javax.swing.GroupLayout(adicionarEscritorDialog.getContentPane());
        adicionarEscritorDialog.getContentPane().setLayout(adicionarEscritorDialogLayout);
        adicionarEscritorDialogLayout.setHorizontalGroup(
            adicionarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adicionarEscritorDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeEscritorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(adicionarEscritorDialogLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(adicionarEscritorButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adicionarEscritorDialogLayout.setVerticalGroup(
            adicionarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adicionarEscritorDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(adicionarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEscritorTextField)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(adicionarEscritorButton)
                .addGap(16, 16, 16))
        );

        nomeEscritorTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEscritorTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome do Escritor:");

        removerEscritorButton.setText("Remover Autor");
        removerEscritorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerEscritorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removerEscritorDialogLayout = new javax.swing.GroupLayout(removerEscritorDialog.getContentPane());
        removerEscritorDialog.getContentPane().setLayout(removerEscritorDialogLayout);
        removerEscritorDialogLayout.setHorizontalGroup(
            removerEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removerEscritorDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeEscritorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(removerEscritorDialogLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(removerEscritorButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removerEscritorDialogLayout.setVerticalGroup(
            removerEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removerEscritorDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(removerEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEscritorTextField1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(removerEscritorButton)
                .addGap(16, 16, 16))
        );

        nomeEscritorTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEscritorTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome do Escritor:");

        pesquisarEscritorButton.setText("Pesquisar Autor");
        pesquisarEscritorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarEscritorButtonActionPerformed(evt);
            }
        });

        informacaoTextArea.setColumns(20);
        informacaoTextArea.setRows(5);
        jScrollPane2.setViewportView(informacaoTextArea);

        javax.swing.GroupLayout pesquisarEscritorDialogLayout = new javax.swing.GroupLayout(pesquisarEscritorDialog.getContentPane());
        pesquisarEscritorDialog.getContentPane().setLayout(pesquisarEscritorDialogLayout);
        pesquisarEscritorDialogLayout.setHorizontalGroup(
            pesquisarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisarEscritorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pesquisarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesquisarEscritorDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pesquisarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarEscritorDialogLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeEscritorTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarEscritorDialogLayout.createSequentialGroup()
                                .addComponent(pesquisarEscritorButton)
                                .addGap(153, 153, 153))))
                    .addGroup(pesquisarEscritorDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        pesquisarEscritorDialogLayout.setVerticalGroup(
            pesquisarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarEscritorDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pesquisarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEscritorTextField2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarEscritorButton)
                .addContainerGap())
        );

        jLabel5.setText("Nacionalidade:");

        pesquisarNacionalidadeButton.setText("Pesquisar Nacionalidade");
        pesquisarNacionalidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarNacionalidadeButtonActionPerformed(evt);
            }
        });

        autoresTextArea.setColumns(20);
        autoresTextArea.setRows(5);
        jScrollPane3.setViewportView(autoresTextArea);

        nomeNacionalidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeNacionalidadeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pesquisarNacionalidadeDialogLayout = new javax.swing.GroupLayout(pesquisarNacionalidadeDialog.getContentPane());
        pesquisarNacionalidadeDialog.getContentPane().setLayout(pesquisarNacionalidadeDialogLayout);
        pesquisarNacionalidadeDialogLayout.setHorizontalGroup(
            pesquisarNacionalidadeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisarNacionalidadeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pesquisarNacionalidadeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesquisarNacionalidadeDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeNacionalidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(pesquisarNacionalidadeDialogLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(pesquisarNacionalidadeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pesquisarNacionalidadeDialogLayout.setVerticalGroup(
            pesquisarNacionalidadeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarNacionalidadeDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pesquisarNacionalidadeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeNacionalidadeTextField)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarNacionalidadeButton)
                .addContainerGap())
        );

        nomeEscritorTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEscritorTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome do Escritor:");

        pesquisarObrasButton.setText("Pesquisar Obras");
        pesquisarObrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarObrasButtonActionPerformed(evt);
            }
        });

        obrasEscritorTextArea.setColumns(20);
        obrasEscritorTextArea.setRows(5);
        jScrollPane4.setViewportView(obrasEscritorTextArea);

        javax.swing.GroupLayout pesquisarObrasEscritorDialogLayout = new javax.swing.GroupLayout(pesquisarObrasEscritorDialog.getContentPane());
        pesquisarObrasEscritorDialog.getContentPane().setLayout(pesquisarObrasEscritorDialogLayout);
        pesquisarObrasEscritorDialogLayout.setHorizontalGroup(
            pesquisarObrasEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisarObrasEscritorDialogLayout.createSequentialGroup()
                .addGroup(pesquisarObrasEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarObrasEscritorDialogLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeEscritorTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pesquisarObrasEscritorDialogLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(pesquisarObrasButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pesquisarObrasEscritorDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
        pesquisarObrasEscritorDialogLayout.setVerticalGroup(
            pesquisarObrasEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarObrasEscritorDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pesquisarObrasEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEscritorTextField4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarObrasButton)
                .addContainerGap())
        );

        jLabel6.setText("Nome do Escritor:");

        alterarEscritorButton.setText("Alterar Informação");
        alterarEscritorButton.setEnabled(false);
        alterarEscritorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEscritorButtonActionPerformed(evt);
            }
        });

        nomeEscritorTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEscritorTextField3ActionPerformed(evt);
            }
        });

        nomeRadioButton.setText("Nome");
        nomeRadioButton.setEnabled(false);

        dNascimentoRadioButton.setText("Data de Nascimento");
        dNascimentoRadioButton.setEnabled(false);

        nacionalidadeRadioButton.setText("Nacionalidade");
        nacionalidadeRadioButton.setEnabled(false);

        ocupacaoRadioButton.setText("Ocupações");
        ocupacaoRadioButton.setEnabled(false);

        dFalecimentoRadioButton.setText("Data de Falecimento");
        dFalecimentoRadioButton.setEnabled(false);

        premiosRadioButton.setText("Prémios");
        premiosRadioButton.setEnabled(false);

        gLiterarioRadioButton.setText("Género Literário");
        gLiterarioRadioButton.setEnabled(false);

        alterarTextField.setEnabled(false);

        jLabel7.setText("Alterar:");

        enviarEscritorButton.setText("Enviar Nome");
        enviarEscritorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarEscritorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarEscritorDialogLayout = new javax.swing.GroupLayout(editarEscritorDialog.getContentPane());
        editarEscritorDialog.getContentPane().setLayout(editarEscritorDialogLayout);
        editarEscritorDialogLayout.setHorizontalGroup(
            editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarEscritorDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dFalecimentoRadioButton)
                        .addGroup(editarEscritorDialogLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nomeEscritorTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editarEscritorDialogLayout.createSequentialGroup()
                            .addGroup(editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nacionalidadeRadioButton)
                                .addComponent(dNascimentoRadioButton)
                                .addComponent(nomeRadioButton))
                            .addGap(66, 66, 66)
                            .addGroup(editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(premiosRadioButton)
                                .addComponent(ocupacaoRadioButton)
                                .addComponent(gLiterarioRadioButton)))
                        .addComponent(alterarTextField)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarEscritorDialogLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(enviarEscritorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alterarEscritorButton)
                .addGap(38, 38, 38))
        );
        editarEscritorDialogLayout.setVerticalGroup(
            editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarEscritorDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEscritorTextField3)
                    .addComponent(jLabel6))
                .addGap(43, 43, 43)
                .addGroup(editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeRadioButton)
                    .addComponent(ocupacaoRadioButton))
                .addGap(18, 18, 18)
                .addGroup(editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacionalidadeRadioButton)
                    .addComponent(gLiterarioRadioButton))
                .addGap(18, 18, 18)
                .addGroup(editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dNascimentoRadioButton)
                    .addComponent(premiosRadioButton))
                .addGap(18, 18, 18)
                .addComponent(dFalecimentoRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(editarEscritorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarEscritorButton)
                    .addComponent(alterarEscritorButton))
                .addGap(24, 24, 24))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane1.setViewportView(outputTextArea);

        jLabel1.setText("Output:");

        principalMenu.setText("Principal");
        principalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalMenuActionPerformed(evt);
            }
        });

        abrirMenuItem.setText("Abrir");
        abrirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMenuItemActionPerformed(evt);
            }
        });
        principalMenu.add(abrirMenuItem);

        sairMenuItem.setText("Sair");
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        principalMenu.add(sairMenuItem);

        jMenuBar1.add(principalMenu);

        xmlMenu.setText("XML");

        adicionarEscritorMenuItem.setText("Adicionar Autor");
        adicionarEscritorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEscritorMenuItemActionPerformed(evt);
            }
        });
        xmlMenu.add(adicionarEscritorMenuItem);

        removerEscritorMenuItem.setText("Remover Autor");
        removerEscritorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerEscritorMenuItemActionPerformed(evt);
            }
        });
        xmlMenu.add(removerEscritorMenuItem);

        editarEscritorMenuItem.setText("Editar escritor");
        editarEscritorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEscritorMenuItemActionPerformed(evt);
            }
        });
        xmlMenu.add(editarEscritorMenuItem);

        jMenuBar1.add(xmlMenu);

        xPathMenu.setText("XPath");

        pesquisarEscritorMenuItem.setText("Pesquisar por escritor");
        pesquisarEscritorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarEscritorMenuItemActionPerformed(evt);
            }
        });
        xPathMenu.add(pesquisarEscritorMenuItem);

        pesquisarNacionalidadeMenuItem.setText("Pesquisar por nacionalidade");
        pesquisarNacionalidadeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarNacionalidadeMenuItemActionPerformed(evt);
            }
        });
        xPathMenu.add(pesquisarNacionalidadeMenuItem);

        pesquisarObrasEscritorMenuItem.setText("Pesquisar obras por escritor");
        pesquisarObrasEscritorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarObrasEscritorMenuItemActionPerformed(evt);
            }
        });
        xPathMenu.add(pesquisarObrasEscritorMenuItem);

        escritorPremiadoMenuItem.setText("Pesquisar escritor mais premiado");
        escritorPremiadoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escritorPremiadoMenuItemActionPerformed(evt);
            }
        });
        xPathMenu.add(escritorPremiadoMenuItem);

        jMenuBar1.add(xPathMenu);

        validarMenu.setText("Validar");

        DTDMenuItem.setText("DTD");
        validarMenu.add(DTDMenuItem);

        XSDMenuItem.setText("XSD");
        validarMenu.add(XSDMenuItem);

        jMenuBar1.add(validarMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMenuItemActionPerformed
        // TODO add your handling code here:
        
        String texto;
        jFileChooser1.showOpenDialog(this);
        String nomeF= jFileChooser1.getSelectedFile().getAbsolutePath();
        try {
            texto=Functions.ler_ficheiro(nomeF);
            if (texto == null){
                JOptionPane.showMessageDialog(this,
                        "Apenas ficheiros XML podem ser abertos!",
                        "Warning",
                        JOptionPane.WARNING_MESSAGE);
            }
            outputTextArea.setText(texto);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirMenuItemActionPerformed

    private void principalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principalMenuActionPerformed

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void adicionarEscritorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEscritorMenuItemActionPerformed
        adicionarEscritorDialog.setSize(500, 200);
        adicionarEscritorDialog.setLocation(200, 200);
        adicionarEscritorDialog.setVisible(true);
    }//GEN-LAST:event_adicionarEscritorMenuItemActionPerformed

    private void nomeEscritorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEscritorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEscritorTextFieldActionPerformed

    private void adicionarEscritorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEscritorButtonActionPerformed
        try {
            Escritores escritor = Wrappers.criaEscritor(nomeEscritorTextField.getText());
            
            if(escritor != null){
                
                Document docEscritor = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
                
                List<Obra> obras = Wrappers.criaObra(nomeEscritorTextField.getText(), escritor.getId());
                
                Document docObras = XMLJDomFunctions.lerDocumentoXML("obras.xml");
                
                if (obras != null && !obras.isEmpty()) {
                    for (Obra obra : obras) {

                        docObras = ObrasXML.adicionaObras(obra, docObras);
                        XMLJDomFunctions.escreverDocumentoParaFicheiro(docObras, "obras.xml");
                    }
                    
                    
                    docEscritor = EscritoresXML.adicionaEscritor(escritor, docEscritor);

                    XMLJDomFunctions.escreverDocumentoParaFicheiro(docEscritor, "escritores.xml");
                    
                    JOptionPane.showMessageDialog(this,
                        "Autor e obras adicionadas com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
                    
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Obras não encontradas",
                        "Informação",
                        JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Escritor já existe no ficheiro",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            adicionarEscritorDialog.setVisible(false);
            nomeEscritorTextField.setText("");
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SaxonApiException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adicionarEscritorButtonActionPerformed

    private void nomeEscritorTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEscritorTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEscritorTextField1ActionPerformed

    private void removerEscritorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerEscritorButtonActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        if(doc == null) {
            JOptionPane.showMessageDialog(this,
                    "Ainda não existe ecritores adicionados",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            //Chama a função para remover  livros ao XML
            doc = EscritoresXML.removeEscritor(nomeEscritorTextField1.getText(), doc);
            //grava o ficheiro XML em disco
            if (doc != null) {
                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "escritores.xml");
                removerEscritorDialog.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Escritor e Obras removidos com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
                nomeEscritorTextField1.setText("");
            } else {
                removerEscritorDialog.setVisible(false);
                JOptionPane.showMessageDialog(this,
                        "Escritor não encontrado",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
                nomeEscritorTextField1.setText("");
            }
        }
    }//GEN-LAST:event_removerEscritorButtonActionPerformed

    private void removerEscritorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerEscritorMenuItemActionPerformed
        removerEscritorDialog.setSize(500, 200);
        removerEscritorDialog.setLocation(200, 200);
        removerEscritorDialog.setVisible(true);
    }//GEN-LAST:event_removerEscritorMenuItemActionPerformed

    private void pesquisarEscritorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarEscritorMenuItemActionPerformed
        pesquisarEscritorDialog.setSize(500, 500);
        pesquisarEscritorDialog.setLocation(200, 200);
        pesquisarEscritorDialog.setVisible(true);
    }//GEN-LAST:event_pesquisarEscritorMenuItemActionPerformed

    private void nomeEscritorTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEscritorTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEscritorTextField2ActionPerformed

    private void pesquisarEscritorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarEscritorButtonActionPerformed

        try {
           List<String> result = XPathFunctions.pesquisa_nome_autor(nomeEscritorTextField2.getText());
           
           if(result != null){
                informacaoTextArea.setText("Informação do autor " + nomeEscritorTextField2.getText() + ":\n\n");
                for (String results : result) {
                    informacaoTextArea.append(results + "\n");
                }
                
                nomeEscritorTextField2.setText("");
            } else {
                JOptionPane.showMessageDialog(this,
                    "Escritor não encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
                nomeEscritorTextField2.setText("");
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pesquisarEscritorButtonActionPerformed

    private void pesquisarNacionalidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarNacionalidadeButtonActionPerformed
        try {
            List<String> result = XPathFunctions.pesquisa_nacionalidade_autor(nomeNacionalidadeTextField.getText());
            if(result != null){
                autoresTextArea.setText("Autores " + nomeNacionalidadeTextField.getText() + ":\n\n");
                for (String results : result) {
                    autoresTextArea.append(results);
                }
                
                nomeNacionalidadeTextField.setText("");
            } else {
                JOptionPane.showMessageDialog(this,
                    "Nacionalidade não encontrada",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
                nomeNacionalidadeTextField.setText("");
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pesquisarNacionalidadeButtonActionPerformed

    private void nomeNacionalidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeNacionalidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeNacionalidadeTextFieldActionPerformed

    private void pesquisarNacionalidadeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarNacionalidadeMenuItemActionPerformed
        pesquisarNacionalidadeDialog.setSize(500, 500);
        pesquisarNacionalidadeDialog.setLocation(200, 200);
        pesquisarNacionalidadeDialog.setVisible(true);
    }//GEN-LAST:event_pesquisarNacionalidadeMenuItemActionPerformed

    private void alterarEscritorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEscritorButtonActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        
        if(doc == null) {
            JOptionPane.showMessageDialog(this,
                    "Ainda não existe ecritores adicionados",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            if (nomeRadioButton.isSelected()) {

                doc = EscritoresXML.editaInformacaoEscritor(nomeEscritorTextField3.getText(),"nome",alterarTextField.getText(),doc);
            } else if (nacionalidadeRadioButton.isSelected()) {

                doc = EscritoresXML.editaInformacaoEscritor(nomeEscritorTextField3.getText(),"nacionalidade",alterarTextField.getText(),doc);
            } else if (dNascimentoRadioButton.isSelected()) {

                doc = EscritoresXML.editaInformacaoEscritor(nomeEscritorTextField3.getText(), "datanascimento", alterarTextField.getText(), doc);
            } else if (dFalecimentoRadioButton.isSelected()) {

                doc = EscritoresXML.editaInformacaoEscritor(nomeEscritorTextField3.getText(), "datafalecimento", alterarTextField.getText(), doc);
            } else if (gLiterarioRadioButton.isSelected()) {
                // Perform actions for gLiterarioRadioButton
                String generoliterario = data.get("generoliterario");

            } else if (ocupacaoRadioButton.isSelected()) {
                // Perform actions for ocupacaoRadioButton
                String ocupacoes = data.get("ocupacoes");

            } else if (premiosRadioButton.isSelected()) {
                // Perform actions for premiosRadioButton
                String premios = data.get("premios");

            }

            if(doc != null){
                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "escritores.xml");
                JOptionPane.showMessageDialog(this,
                        "Informação atualizada",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {

                JOptionPane.showMessageDialog(this,
                        "Escritor não encontrado",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            }

            nomeEscritorTextField3.setText("");
            alterarTextField.setText("");

            // Reset radio buttons
            nomeRadioButton.setSelected(false);
            nacionalidadeRadioButton.setSelected(false);
            dNascimentoRadioButton.setSelected(false);
            dFalecimentoRadioButton.setSelected(false);
            gLiterarioRadioButton.setSelected(false);
            ocupacaoRadioButton.setSelected(false);
            premiosRadioButton.setSelected(false);

            // Reset other dialog components as needed

            // Enable or disable components
            nomeEscritorTextField3.setEditable(true);
            alterarTextField.setEnabled(false);
            alterarEscritorButton.setEnabled(false);

            // Clear button group selection
            buttonGroup.clearSelection();

            nomeRadioButton.setEnabled(false);
            nacionalidadeRadioButton.setEnabled(false);
            dNascimentoRadioButton.setEnabled(false);
            dFalecimentoRadioButton.setEnabled(false);
            gLiterarioRadioButton.setEnabled(false);
            ocupacaoRadioButton.setEnabled(false);
            premiosRadioButton.setEnabled(false);

            enviarEscritorButton.setEnabled(true);
        }
    }//GEN-LAST:event_alterarEscritorButtonActionPerformed

    private void nomeEscritorTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEscritorTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEscritorTextField3ActionPerformed

    private void enviarEscritorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarEscritorButtonActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        if(doc == null) {
            JOptionPane.showMessageDialog(this,
                    "Ainda não existe ecritores adicionados",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            data = EscritoresXML.verificaEscritor(nomeEscritorTextField3.getText(), doc);
            nomeEscritorTextField3.setEditable(false);
            alterarTextField.setEnabled(true);
            enviarEscritorButton.setEnabled(false);
            if (data.containsKey("nome")) {
                nomeRadioButton.setEnabled(true);
                buttonGroup.add(nomeRadioButton);
            }
            if (data.containsKey("nacionalidade")) {
                nacionalidadeRadioButton.setEnabled(true);
                buttonGroup.add(nacionalidadeRadioButton);
            }
            if (data.containsKey("datanascimento")) {
                dNascimentoRadioButton.setEnabled(true);
                buttonGroup.add(dNascimentoRadioButton);
            }
            if (data.containsKey("datafalecimento")) {
                dFalecimentoRadioButton.setEnabled(true);
                buttonGroup.add(dFalecimentoRadioButton);
            }
            if (data.containsKey("generoliterario")) {
                gLiterarioRadioButton.setEnabled(true);
                buttonGroup.add(gLiterarioRadioButton);
            }
            if (data.containsKey("ocupacoes")) {
                ocupacaoRadioButton.setEnabled(true);
                buttonGroup.add(ocupacaoRadioButton);
            }
            if (data.containsKey("premios")) {
                premiosRadioButton.setEnabled(true);
                buttonGroup.add(premiosRadioButton);
            }

            nomeRadioButton.addActionListener((ActionEvent e) -> {
                alterarTextField.setText(data.get("nome"));
                alterarEscritorButton.setEnabled(true);
            });

            nacionalidadeRadioButton.addActionListener((ActionEvent e) -> {
                alterarTextField.setText(data.get("nacionalidade"));
                alterarEscritorButton.setEnabled(true);
            });

            dNascimentoRadioButton.addActionListener((ActionEvent e) -> {
                alterarTextField.setText(data.get("datanascimento"));
                alterarEscritorButton.setEnabled(true);
            });

            dFalecimentoRadioButton.addActionListener((ActionEvent e) -> {
                alterarTextField.setText(data.get("datafalecimento"));
                alterarEscritorButton.setEnabled(true);
            });
        }
    }//GEN-LAST:event_enviarEscritorButtonActionPerformed

    private void editarEscritorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEscritorMenuItemActionPerformed
        editarEscritorDialog.setSize(500, 500);
        editarEscritorDialog.setLocation(200, 200);
        editarEscritorDialog.setVisible(true);
    }//GEN-LAST:event_editarEscritorMenuItemActionPerformed

    private void nomeEscritorTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEscritorTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEscritorTextField4ActionPerformed

    private void pesquisarObrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarObrasButtonActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        String id = null;
        if(doc != null){
            id = EscritoresXML.getIdEscritor(nomeEscritorTextField4.getText(), doc);
            
            if(id != null){
                try {
                    List<String> result = XPathFunctions.pesquisa_obras_autor(id);
                    if(result != null){
                        obrasEscritorTextArea.setText("Obras do escritor " + nomeEscritorTextField4.getText() + ":\n\n");
                        for (String results : result) {
                            obrasEscritorTextArea.append(results);
                        }

                        nomeEscritorTextField4.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this,
                            "Obras não encontradas",
                            "Informação",
                            JOptionPane.INFORMATION_MESSAGE);
                        nomeEscritorTextField4.setText("");
                    }
                } catch (SaxonApiException ex) {
                    Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Escritor não encontrado",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Ainda não existe ecritores adicionados",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_pesquisarObrasButtonActionPerformed

    private void pesquisarObrasEscritorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarObrasEscritorMenuItemActionPerformed
        pesquisarObrasEscritorDialog.setSize(500, 500);
        pesquisarObrasEscritorDialog.setLocation(200, 200);
        pesquisarObrasEscritorDialog.setVisible(true);
    }//GEN-LAST:event_pesquisarObrasEscritorMenuItemActionPerformed

    private void escritorPremiadoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escritorPremiadoMenuItemActionPerformed
        
        try {
            String resultado = XPathFunctions.escritor_mais_premiado();
            if(resultado != null){
               JOptionPane.showMessageDialog(this,
                    "O escritor com mais prémios é: " + resultado,
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE); 
            } else {
                JOptionPane.showMessageDialog(this,
                    "Ainda não existe ecritores com prémios",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (SaxonApiException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_escritorPremiadoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DTDMenuItem;
    private javax.swing.JMenuItem XSDMenuItem;
    private javax.swing.JMenuItem abrirMenuItem;
    private javax.swing.JButton adicionarEscritorButton;
    private javax.swing.JDialog adicionarEscritorDialog;
    private javax.swing.JMenuItem adicionarEscritorMenuItem;
    private javax.swing.JButton alterarEscritorButton;
    private javax.swing.JTextField alterarTextField;
    private javax.swing.JTextArea autoresTextArea;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton dFalecimentoRadioButton;
    private javax.swing.JRadioButton dNascimentoRadioButton;
    private javax.swing.JDialog editarEscritorDialog;
    private javax.swing.JMenuItem editarEscritorMenuItem;
    private javax.swing.JButton enviarEscritorButton;
    private javax.swing.JMenuItem escritorPremiadoMenuItem;
    private javax.swing.JRadioButton gLiterarioRadioButton;
    private javax.swing.JTextArea informacaoTextArea;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton nacionalidadeRadioButton;
    private javax.swing.JTextField nomeEscritorTextField;
    private javax.swing.JTextField nomeEscritorTextField1;
    private javax.swing.JTextField nomeEscritorTextField2;
    private javax.swing.JTextField nomeEscritorTextField3;
    private javax.swing.JTextField nomeEscritorTextField4;
    private javax.swing.JTextField nomeNacionalidadeTextField;
    private javax.swing.JRadioButton nomeRadioButton;
    private javax.swing.JTextArea obrasEscritorTextArea;
    private javax.swing.JRadioButton ocupacaoRadioButton;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JButton pesquisarEscritorButton;
    private javax.swing.JDialog pesquisarEscritorDialog;
    private javax.swing.JMenuItem pesquisarEscritorMenuItem;
    private javax.swing.JButton pesquisarNacionalidadeButton;
    private javax.swing.JDialog pesquisarNacionalidadeDialog;
    private javax.swing.JMenuItem pesquisarNacionalidadeMenuItem;
    private javax.swing.JButton pesquisarObrasButton;
    private javax.swing.JDialog pesquisarObrasEscritorDialog;
    private javax.swing.JMenuItem pesquisarObrasEscritorMenuItem;
    private javax.swing.JRadioButton premiosRadioButton;
    private javax.swing.JMenu principalMenu;
    private javax.swing.JButton removerEscritorButton;
    private javax.swing.JDialog removerEscritorDialog;
    private javax.swing.JMenuItem removerEscritorMenuItem;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JMenu validarMenu;
    private javax.swing.JMenu xPathMenu;
    private javax.swing.JMenu xmlMenu;
    // End of variables declaration//GEN-END:variables
}
